###
GET http://localhost:3003/test 

###
POST http://localhost:3003/createUser 
Content-Type: application/json

{
    "name": "Guilherme",
    "email": "guilherme@email.com",
    "password": "6767676"
}

###

GET http://localhost:3003/allUsers 